FROM mysql:8.0.28-oracle

ENV MYSQL_ALLOW_EMPTY_PASSWORD=true
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=secret
ENV MYSQL_DATABASE=deeprespredDB

#COPY ./init.sql /docker-entrypoint-initdb.d/
#COPY ./init.sql .
